apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: home-automation
  namespace: argocd
spec:
  description: My home automation project
  sourceRepos:
    - '*'
  sourceNamespaces:
    - '*'
  destinations:
    - namespace: '*'
      server: '*'
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'