---
global:
  domain: argocd.kubernetes.lan.basmaas.nl

server:
  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-stg
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
      nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
      nginx.ingress.kubernetes.io/whitelist-source-range: 10.42.0.0/0
    hosts:
      - argocd.kubernetes.lan.basmaas.nl
    https: true
    tls:
      - secretName: argocd.kubernetes.lan.basmaas.nl
        hosts:
          - argocd.kubernetes.lan.basmaas.nl

dex:
  enabled: false

notifications:
  enabled: false

configs:
  cm:
    create: true
    helm.valuesFileSchemes: >-
      secrets

  cmp:
    create: true
    plugins:
      cmp-sops-decrypt:
        generate:
          command: [bash, -ec]
          args:
            - |
              cd $(git rev-parse --show-toplevel)
              chmod +x ./.mise/tasks/build/kustomization.sh 1>/
              mise run ./.mise/tasks/build/kustomization.sh "${ARGOCD_APP_SOURCE_PATH}"
          discover:
            fileName: "values.enc.yaml"
          preserveFileMode: false
