#!/bin/sh
# Generated with mise: https://mise.jdx.dev/cli/generate/git-pre-commit.html
STAGED="$(git diff-index --cached --name-only HEAD | tr ' ' '\ ' | tr '\n' ' ' | xargs)"
export STAGED
export MISE_PRE_COMMIT=1
exec mise run lint
