synology-csi:
    clientInfoSecret:
        clients:
            - host: 192.168.8.126
                port: 5000
                https: false
                username: bas
                password: 'J@iv7%7b%QwzkCJ!ByqUDnw6*Frvz'
        create: true
