synology-csi:
    clientInfoSecret:
        clients:
            - host: ENC[AES256_GCM,data:WDolvT3SmdO9feD0+g==,iv:S064ntSbHxcuLz+kFrTofeQz2OEbmdEL82ntJF6tZEo=,tag:MOnBElJSnjVPUUrJI2Y+Qw==,type:str]
              port: ENC[AES256_GCM,data:Bpg5iQ==,iv:NVw9OZ2lMAaj+zADXseB5KWOY9E/WAgk599ECmZVBMI=,tag:gyDzcraOnM/d0ttt8p2RVA==,type:int]
              https: ENC[AES256_GCM,data:PVJrvNA=,iv:Q3Uz4bpwcKzZfxC66E8YxuRdMGb2aymrZExTKag4k/k=,tag:c0HbRrHDYSjhO2yWd0mOfw==,type:bool]
              username: ENC[AES256_GCM,data:+Hl+,iv:f8Te410K8e29l0J7/ghO72wrykXuKI1yaEW8iYOfIBc=,tag:gzXt2Kd0WG9aFabQZUvXTg==,type:str]
              password: ENC[AES256_GCM,data:qhazLdb+PgTNd93r9StScgefAyrp4K06T+Ed9zQ=,iv:MzA5cnnK5akNaFobod/c924nIHaV9uQXlVn/mwBOALw=,tag:SIajUlGF7DhaFVqVn4wjrA==,type:str]
        create: ENC[AES256_GCM,data:WrLo+w==,iv:XEaNGt3TBr3/W+95euHSL2XVe8ZOFYag2A25CRWuPiw=,tag:Beo7d2OKl+m/n34BA7ouiQ==,type:bool]
sops:
    kms: []
    gcp_kms: []
    azure_kv:
        - vault_url: https://sops-3caeb0533c5a473f.vault.azure.net
          name: sops-key
          version: b2031a08aea14a50ab6d8e72548eb4f9
          created_at: "2025-05-20T11:01:36Z"
          enc: r7eoLx3JEOuBu8r6qmqFdf9-4mdvgBV4drSKxpxvQnMtmHTzP53pcOrGiedMtvBFeTS5eTch4TpwBbZuXMpgrYxiyQRzhJwGAEC9rvfPAJ50-TOD8uveKqIGL-kIVV9NxPOt2x-y5P3bwv-7mQqDndwv2-KXpaN-sNLA0q1YMnX-FGaRFyZQX6jIsysWbBK56h6VXfy8Fnop8Jm3e5b0ls2mmpkim7vTqYOebgipTHGynv8K0lgpWFaWBNpixbaIG3d-1Vm_oPhphb-DdFg3ZZYoMHTsX44A6DEMQ6ZlFYtJ6mG0PCVq-hLKpz1BPnaukPucI0jm-G_FbJlN_TdItA
    hc_vault: []
    age: []
    lastmodified: "2025-05-20T11:01:36Z"
    mac: ENC[AES256_GCM,data:joUGbyUCaCqUkBPIbz41O/Rkhq/y5jQb+gQUU75/0sHONqFPs7lC2TzzzUyYfnrfO3noZ4LzLEU4OmXC2acRpQT5q4x+nAjdb48t/uNgBla85fFuztxZI7/yr1IVCYIMiSHycVnNShBPQYzlP78cDsZtQJR8tZwXrCThBxoRfys=,iv:AZQ887KnDeCWPa067Smp8l8og1wIy+QmucyWtatgM8k=,tag:W1fJ/N4dN3fa6UKI20ZqUQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.2
