apiVersion: ENC[AES256_GCM,data:Rocqo1iv7oP3vdHGvuIYXuMz,iv:szvD5/i7HSLVp2lK/pl7RztMMlNZTQRU0TmekgXb1Jw=,tag:kJmIgC5paPzFgXWYxWhAoA==,type:str]
kind: ENC[AES256_GCM,data:vAidxkm1lQmS3UibLA==,iv:2uQb6AwoQcie5VYEwyXJhvk3eg+9CPzKdvJl0GwEQ9Y=,tag:/f9y2p72IP782kkyjIj6Kg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:xCI5n3Mi07cXLOJGx9RMOLmy4g==,iv:30le8OWzA/W3p45pRtRiC4YP2FdIg/sgZvBU+oKXjyE=,tag:qh269NRjKm4DN0F0JKDoPA==,type:str]
spec:
    addresses:
        - ENC[AES256_GCM,data:r7INNvARkcxPF7hypg+RDwS+E6BVEqbR4btH,iv:dIp2koLOEWFA7hje0GpVqHRRMGjctelqunn9enljITU=,tag:LeKhbwVGPEOXiwv1EGb3Xg==,type:str]
    autoAssign: ENC[AES256_GCM,data:TzwoIQ==,iv:yRuR9/l+oXEm2Db0J8CwsGHllrINwjSUfp5rNmIR5hg=,tag:vwOdeRW74ltxWTo2nhV9JQ==,type:bool]
    avoidBuggyIPs: ENC[AES256_GCM,data:3hKys5o=,iv:AsdGPF2ZDWOpXGx+Q8JSl5CohaVjrGjDxoMOlZSU/G4=,tag:wt2aJcuXghhhusZ+jtlpBQ==,type:bool]
sops:
    kms: []
    gcp_kms: []
    azure_kv:
        - vault_url: https://sops-3caeb0533c5a473f.vault.azure.net
          name: sops-key
          version: b2031a08aea14a50ab6d8e72548eb4f9
          created_at: "2025-07-15T20:48:23Z"
          enc: Tdi3cR3hUF7CRNR-gCkKBFd-Pl-bCO5xnE39CpgpoYZ7I57Hru5HoDfEGpUYBoz8t2Ega9Kt_JzA-VbbkKtYKCo62xubs3cK6KrQJwDYJTVstW700G8meXwVPZPfqYY0wJmOpQV_xVXxQUhGb9IywICkgM_Y0xvB7vqLF2PE50DE6U_KPrfoCvDumYelIA-m7aucyEKFak8oxQ5VAIcnIWuKRa3dulR_mujJ8iHcYhbzcBIWiM_eb48VG54xwiu2jgki2KqBb04yPgCDcWdUOv72rLU-rUeoFRw4IpCBPEM4goyA77D2TX7X2KRAGtQLJqOTpify3ejpR9sox14l3w
    hc_vault: []
    age: []
    lastmodified: "2025-07-15T20:48:24Z"
    mac: ENC[AES256_GCM,data:CjUD+ixtxfIjTW5+hBzWqPjaY3Qat3GBc6kbJYfibnhpD0tMwAQS/LqUZgypaoh+D9wmakjpg9gTtQR3h5p4AbOytIKp5ohhAqN9fhkQU5iK665GkuNVfkHUE/m+14H/AK2mwfXQYAhTuDq7bHNbVs2zJ27Z4TzmA5nvyaNdsfw=,iv:Qpe0RyJimeJIKBkZcXg8OJN9gDcX28j4MZJMhgmL+Qk=,tag:yCZ93ib/7nwZ+wtq5R0VEQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.2
