---
grafana:
  persistence:
    enabled: true
    size: 10Gi
    storageClassName: nfs   # Temporarily set to NFS

  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-stg
    hosts:
      - grafana.kubernetes.lan.basmaas.nl
    tls:
      - secretName: grafana.kubernetes.lan.basmaas.nl
        hosts:
          - grafana.kubernetes.lan.basmaas.nl

  securityContext:
    runAsNonRoot: false   # Needed for NFS
