---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: k8s-homelab-apps
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/bamaas/Homelab-2.0.git
    targetRevision: main
    path: apps
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
