[tools]
k9s = "0.32.7"
kubectl = "1.29.11"
mc = "latest"
sops = "3.9.2"
talos = "1.9.5"
terraform = "1.10.1"

[tasks.terraform]
run = "terraform"

[env]
TERRAFORM_DIR = "terraform"
ROOT_DIR = "{{cwd}}"
_.file = ".env.dec.json"
KUBECONFIG = "kubeconfig"
TALOSCONFIG = "talosconfig"
TF_LOG = "info"