[tools]
argocd = { version = "latest", exe = "argocd" }
helm = "3.17.2"
helm-diff = "3.10.0"
helmfile = "0.171.0"
k9s = "0.32.7"
kubectl = "1.29.11"
shellcheck = "0.10.0"
sops = "3.9.2"
talos = "1.9.5"
terraform = "1.10.1"
uv = "0.6.11"
yamllint = "1.37.0"

[env]
ROOT_DIR = "{{cwd}}"
TERRAFORM_DIR = "${env.ROOT_DIR}/terraform"
KUBECONFIG = "{{env.ROOT_DIR}}/.config/kubeconfig"
TALOSCONFIG = "{{env.ROOT_DIR}}/.config/talosconfig"
_.file = ".env.dec.json"
TF_LOG = "info"
