---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: l2-advertisement
spec:
  ipAddressPools:
    {{- range .Values.ipAddressPools }}
    {{- if .layer2Advertisement }}
    - {{ .name }}
    {{- end }}
    {{- end }}
