#!/usr/bin/env bash
#MISE description="Install Argo CD"
set -e

ARGOCD_SYSTEM_DIR=${ROOT_DIR}/argocd-system

echo "Installing Argo CD"
helmfile apply \
    -f ${HELMFILE_PATH} \
    ${ARGOCD_SYSTEM_DIR}/helmfile.yaml \
    --kubeconfig=${KUBECONFIG} \
    --quiet