#!/usr/bin/env bash
#MISE description="Install Argo CD"
set -e

ARGOCD_SYSTEM_DIR=${ROOT_DIR}/argocd-system

# echo "Installing Argo CD"
# helmfile apply \
#     -f ${HELMFILE_PATH} \
#     ${ARGOCD_SYSTEM_DIR}/helmfile.yaml \
#     --kubeconfig=${KUBECONFIG} \
#     --quiet

echo "Installing Argo CD"
helm repo add argo-cd $(yq e '.dependencies[0].repository' ${ARGOCD_SYSTEM_DIR}/Chart.yaml)
helm dependency update ${ARGOCD_SYSTEM_DIR}
helm upgrade \
    --install \
    argocd \
    ${ARGOCD_SYSTEM_DIR} \
    --namespace argocd \
    --create-namespace \
    --wait
