#!/usr/bin/env bash
#MISE description="Lint the repo"
set -e

echo "Linting YAML files..."
yamllint . -c ${ROOT_DIR}/.lint/yamllint.yaml

# # shellcheck disable=SC2046
# echo "Linting shell scripts..."
# shellcheck $(find . -name "*.sh")

echo "Validating Terraform code..."
terraform -chdir=${TERRAFORM_DIR} validate