---
zenml:
  zenml:

    ingress:
      enabled: true
      className: "nginx"
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prd
        nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
        kubernetes.io/tls-acme: "true"
      host: zenml.kubernetes.lan.basmaas.nl

    analyticsOptIn: false
