podLabels:
    something: ENC[AES256_GCM,data:ecw/pw==,iv:wpB0JDb6Y8AeXcIVgRQ3pOjQMsLN3zS4XOqxnlNskTE=,tag:z6BPQ6YyiNHs/kqR+JM7Pw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv:
        - vault_url: https://sops-3caeb0533c5a473f.vault.azure.net
          name: sops-key
          version: b2031a08aea14a50ab6d8e72548eb4f9
          created_at: "2025-07-14T19:48:39Z"
          enc: gV9u5C04ZHiOpv0ECAfBEycViIAC7Yf-pGEJou63mH1loJIy6_ZzgD-MuSkfBPyGAvuV-BNx3-yvmYuMaguY9icKYsu1Fe_p6ol-9EmHfI9vrEVkAOozOLkzu5dVcJov9IOsUj56_O-uBcEjmQl-RSjXEWiHIkc9uBIPsPHsptk-2SOq_zlN1i02UmmBKtOt8amscz5nvfdc9qYDQ-VY4xwWvM8F5NITEZa343XNq5e97MYrdozw1M6y91A_TQs5zPb8yfr236m-h2JA7pRJJx0MYQTKu3TBxvaFh7f9oZJonkwZfcRoqgKnm8Jr9DwzIQy8kv4KrBoJQdORIKu3gA
    hc_vault: []
    age: []
    lastmodified: "2025-07-14T19:48:40Z"
    mac: ENC[AES256_GCM,data:XLPUwtG1vMW8Jd7NXAWOM50Br21YjR9GLWqGV5UmyOok4JZXlcdtkPXh/Rmlb+0R72Drc2vRjWyrIOPhly2m0ipv6e1DuL+gFPsdOhfjDrgC9tfmGHV0o9V7F6lOyNKsyosC2MgNkU8L8Cn5wMQh9xtzX6P2Ll6jNuZLvXuahis=,iv:VrvtoHbbiFR6JNhwFdU89LSAbj4qTlQ96DNHilgHU9c=,tag:TFgogbS5dJhBuGlqvXHLNA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.2
