---

resources:
  - ../../../../base/pihole

patches:

  # Set ingress

  - target:
      kind: Ingress
      name: .*
    patch: |-
      - op: add
        path: /spec/rules/0/host
        value: pihole.dev.kubernetes.lan.basmaas.nl

      - op: add
        path: /spec/tls
        value:
          - hosts:
              - pihole.dev.kubernetes.lan.basmaas.nl
            secretName: pihole.dev.kubernetes.lan.basmaas.nl

      - op: add
        path: "/metadata/annotations/cert-manager.io~1cluster-issuer"
        value: letsencrypt-prd

  # Set dns service ip

  - target:
      kind: Service
      name: pihole-dns.*
    patch: |-
      - op: add
        path: /spec/loadBalancerIP
        value: 192.168.8.111

  # Set password

  - target:
      kind: Secret
      name: pihole-password
    patch: |-
      - op: remove
        path: /data/password

  - target:
      kind: Secret
      name: pihole-password
    path: secret-patch.enc.yaml
