---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: external-secrets
  namespace: external-secrets
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - list:
        elements:
          - env: dev
            version: 0.15.1
  template:
    metadata:
      name: external-secrets
    spec:
      # The project the application belongs to.
      project: foundation

      sources:
        - repoURL: https://charts.external-secrets.io
          chart: external-secrets
          targetRevision: '{{.version}}'
          helm:
            valueFiles:
              - $values/config/external-secrets/common.yaml
              - $values/config/external-secrets/{{.env}}.yaml
        - repoURL: 'https://github.com/bamaas/Homelab-2.0.git'
          targetRevision: HEAD
          ref: values

      # Destination cluster and namespace to deploy the application
      destination:
        server: https://kubernetes.default.svc
        namespace: external-secrets

      # Sync policy
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
        automated:
          prune: true
          selfHeal: true
