---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: node-red
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - list:
        elements:
          - env: dev
            version: 0.29.0
  template:
    metadata:
      name: node-red
    spec:
      # The project the application belongs to.
      project: home-automation

      sources:
        - repoURL: https://schwarzit.github.io/node-red-chart/
          chart: node-red
          targetRevision: '{{.version}}'
          helm:
            valueFiles:
              - $values/config/node-red/common.yaml
              - $values/config/node-red/{{.env}}.yaml
        - repoURL: 'https://github.com/bamaas/Homelab-2.0.git'
          targetRevision: HEAD
          ref: values

      # Destination cluster and namespace to deploy the application
      destination:
        server: https://kubernetes.default.svc
        namespace: node-red

      # Sync policy
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
        automated:
          prune: true
          selfHeal: true
