---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: vault
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - list:
        elements:
          - env: dev
            version: 0.30.0
  template:
    metadata:
      name: vault
    spec:
      # The project the application belongs to.
      project: foundation

      sources:
        - repoURL: https://helm.releases.hashicorp.com
          chart: vault
          targetRevision: '{{.version}}'
          helm:
            valueFiles:
              - $values/config/vault/common.yaml
              - $values/config/vault/{{.env}}.yaml
        - repoURL: 'https://github.com/bamaas/Homelab-2.0.git'
          targetRevision: HEAD
          ref: values

      # Destination cluster and namespace to deploy the application
      destination:
        server: https://kubernetes.default.svc
        namespace: vault

      # Sync policy
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
        automated:
          prune: true
          selfHeal: true
