gofit:
    users:
        - email: ENC[AES256_GCM,data:1BtZ/HGCu85lIiQ+2Q==,iv:2Q9YLw2mwmD9Kn1+bwZPWg6GzPAX7RugMx0HscHSqTg=,tag:FpszjsljF70iyAST1PHLQw==,type:str]
          password: ENC[AES256_GCM,data:OfKwWuXKqQM=,iv:39BvVG6SMuOWue+cTX047VEnHLVqivGULYVV2g86LHA=,tag:FD2TliUwIfTfWAYba24w4A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv:
        - vault_url: https://sops-3caeb0533c5a473f.vault.azure.net
          name: sops-key
          version: b2031a08aea14a50ab6d8e72548eb4f9
          created_at: "2025-05-20T17:08:07Z"
          enc: PUe2ehhcEoDJnXvQm8Ivpb5In83U2jO6isTb-l8w8i1qVG-vyqNoLs3mgv2PLPuijQZ5Fc7-QXWcSweU-rt-e3u7Iuu2kMvm2cDZ1XaxMByhZIxK56_8iel2Y66zeVPbDIi-WF2fVaBEEREKS-Innw0S405jvZWGVd0elb3OUbHrfPJgiIwh45mI0M5aDr3NJU_n-B__DT09CgokqK6ikgLdYesVMRk8EQjIJWBCUTdgVl1TIjza-kbcNKA1Yxs8AAwtg4sTfDSCeImEauY3ks43CVhIkEWUcezDLSFTb1sZVuHZ0uJzm646J_laMxuQO7ylfoP59ET2PPgAwVJIUg
    hc_vault: []
    age: []
    lastmodified: "2025-05-20T17:08:07Z"
    mac: ENC[AES256_GCM,data:5nPCnov0uClKTGiSS5FaHhnJDnkhzpwVxSBVVlZHKxwSfUtWVWYQnW4/HZQasma9U/Vk5UdfN1HFt0ghVgM9RwhkRqrgwHh+XhbyIg/U6+T24CiXhRsz1jIneLe0PBa1pU43oThQpT6bsBX0cfee4Txb3LTnT00sYpbqILfkHfg=,iv:vcnssncqwh7zIUeVzHuBYW/mgYY+IgIjR8s93zMtzhE=,tag:2i05T9a25l6fYQgK50VorA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.2
