metallb:
    ipAddressPools:
        - name: ENC[AES256_GCM,data:9iNz5/5h0iuVAK0v/rIviQg=,iv:FKrKYHv7B+5X2/bzq6O0WNHUu2LfQkF15Hk7OJ3UVOg=,tag:Y3HydiJ/s/CqBZ2y62k/Ug==,type:str]
          addresses:
            - ENC[AES256_GCM,data:quR9Dw0ir3PMJIlq2qCfnFb55SU0CHWJaTzo,iv:9YYsvtM2lgO2fXrvAhD60f0OMmc1NgW6Eti3lDUFMCk=,tag:1KkNORc/9UOC9tcZJnLMog==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv:
        - vault_url: https://sops-3caeb0533c5a473f.vault.azure.net
          name: sops-key
          version: b2031a08aea14a50ab6d8e72548eb4f9
          created_at: "2025-05-25T15:42:37Z"
          enc: rjOvNwJGQN7pPtJp-Y36urgh_nq2kjCcm1OfKUpl8-6YyDiOjZacfkQ-nMLR3LsaZsigQY1C72EwBCoz91nRQ83MTCd7fOYbj34QkvF2g41TNpnHhzrc12REOYnNsV6vFwcH8x-ttXxglzSceTdGfsRHrA_v-Qn4nSBeqrsMmsstDRPi-P8K63XDfGR8jo24Ebr_RihGUUcjLP3OvTBA56Nd6y2xJVSVY0qgIFKLlLDOZiWmzGDsgamwizKiKdlMh29QYibP952tiogCrMSmyoytNXnuZlmqvtHcBlHHOWWKtLSuftmZ1WendT5LHzmTuHouI5Hf6NIuojPXrCrXwQ
    hc_vault: []
    age: []
    lastmodified: "2025-05-25T15:42:37Z"
    mac: ENC[AES256_GCM,data:IGv+1Wi+LwXVKOdbuBm12v+gd9FR79nFtlYwUC2A6dTYjcfBI2GTqZtsPBZtJRTosYao2XEU85m80wZvAKr9t0gEpl5I7tO+6b8a3E0i+pIepAjMvGshazTWBjcS52SqURZDregH1q9Vh7b+x3ZrPeZ+HV9x5ha6Vo/9EzYJs5Y=,iv:qKotQGzZHD0ixnUcZBow+68h+fSxWxinNXyekIX5xSg=,tag:YGXO+GL4MsU99SSkBBS9YQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.2
